services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: socialapp-postgres
    container_name: socialapp-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
